import type { NextPage } from 'next';
import Head from 'next/head';

import { Season } from '../../components/home/Season';

const Home: NextPage = () => {
  return (
    <div className="bg-background w-full h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Season />
    </div>
  );
};

export default Home;
